project_id = "cinbnmlfpffmyjmkwbco"

[functions.geocode]
verify_jwt = false

[functions.submit-questionnaire]
verify_jwt = false

[functions.enqueue-answer]
verify_jwt = false

[functions.sentry-tunnel]
verify_jwt = false

[functions.planner-chat]
verify_jwt = false

[functions.location-autocomplete]
verify_jwt = false

[functions.nearest-airports]
verify_jwt = false

[functions.destination-fact]
verify_jwt = false
